### PR TITLE
Updates dependencies

### PR DESCRIPTION
**Pull request by helrond**
Bumps dependencies in package.json and re-makes package.lock. There is one dependency I haven't updated yet (react-scripts) because it's a major version change and is breaking things.

### CODE REVIEW

**Review by p-galligan — APPROVED** [review]
Seems to build fine for me, and the package.json file looks good.

**Comment by HaSistrunk** [comment]
When I run `yarn install` I see an error:

> error pretty-format@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.9.0"
error Found incompatible module.

But I'm able to start dimes with no problems.

**Comment by helrond** [comment]
@HaSistrunk I'm unable to reproduce that locally. I'm also not seeing that in the [CI build](https://travis-ci.com/github/RockefellerArchiveCenter/dimes/builds/231514389). @p-galligan were you seeing this error?

**Comment by p-galligan** [comment]
> @HaSistrunk I'm unable to reproduce that locally. I'm also not seeing that in the [CI build](https://travis-ci.com/github/RockefellerArchiveCenter/dimes/builds/231514389). @p-galligan were you seeing this error?

Nope, I got some deprecation warnings when building, but otherwise it installed and built fine.

**Comment by helrond** [comment]
@HaSistrunk can you try deleting your node_modules directory and then running `yarn install` again to see if you still get this message?

**Review by bonniegee — APPROVED** [review]

**Comment by HaSistrunk** [comment]
> @HaSistrunk can you try deleting your node_modules directory and then running `yarn install` again to see if you still get this message?

I tried that and I did still get the message. However, I believe I needed to upgrade my version of node. I've got it working now with no errors.

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
