### PR TITLE
Allows users to add, delete and view items added to their list

### LINKED ISSUE #52: Allow users to save, fetch and delete data about records
## Is your feature request related to a problem? Please describe.
Users need to be able to save, delete and retrieve data about records. 

## Describe the solution you'd like
Create handlers to save, retrieve and delete data from localStorage, which will persist that data in a user's browser. 

## Additional context
A more robust authentication layer would allow us to separate this data from a user's browser. However, that is out of scope for the initial phase of DIMES development.

### PR DESCRIPTION
**Pull request by helrond**
To test this (you'll need Argo running against Elasticsearch as well):
- go to `/records` and click on one or more of those "add to list" buttons. Observe the MyList count incrementing.
- Go to `/list` and observe the items you just added.
- Click on the remove button to remove a single item
- click on the remove all items to clear the list (in both Desktop and Mobile dropdown)

fixes #52

### CODE REVIEW

**Comment by HaSistrunk** [comment]
The build is failing with: 
```
./src/App.js
  Line 34:17:  'key' is assigned a value but never used
```

Is the build failing because it's calling `key` in another component?

**Comment by helrond** [comment]
@HaSistrunk yep, that's a bug that I need to fix. I'll mark this as ready for review when it's good to go.

**Comment by HaSistrunk** [comment]
After adding the items in `/records`, I see the MyList count change, but I'm still seeing "No saved items." on the /list page.

**Comment by helrond** [comment]
> After adding the items in `/records`, I see the MyList count change, but I'm still seeing "No saved items." on the /list page.

If you look in the console and see a bunch of 404s then you need to have Argo running and targeting dev Elasticsearch.

**Comment by HaSistrunk** [comment]
Cool, this all works for me! I was trying to resolve that `Can't perform a React state update on an unmounted component` error with no luck, but I see you have a TODO noted for that.

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
