### PR TITLE
Updates react-router-dom

### PR DESCRIPTION
**Pull request by helrond**
This is a major update and required converting all class-based components to functional components. Ultimately this is a win for application stability and maintainability because it encourages smaller and more isolated units of code.

### CODE REVIEW

**Comment by HaSistrunk** [comment]
Alright! A couple things I see:
1. I see some weirdness with the resultsCount values after faceting search results. To reproduce: search in dimes, open "Filters" and select any item to facet results. Notice the results summary text changes to read "0-1 of ... results" instead of giving the accurate start and end numbers.
2. When I have items added to my list, the My List page won't load. I'm seeing a few errors in the console including CORS errors and errors pointing to the SavedItemGroup component. To reproduce: Add 1 or more items to your list, go to the My List page.

**Comment by helrond** [comment]
Awesome, thanks for this review. Both of these problems should now be resolved:
- Turns out this was happening anytime there was less than one page of results. I clarified the logic for setting the endItem.
- This was a result of the Request Broker not being available in your local environment. I updated a useEffect hook so that it will only be executed if the Request Broker is available.

**Comment by HaSistrunk** [comment]
Ok great, looks good. One more thing on the My List page:
1. `removeAllListItems` needs review. It currently doesn't take effect until the page is refreshed. To reproduce in the interface: Add one or more items to list, click "Remove all Items" button on My List page, click "Remove". Notice that you have to close the modal and refresh the page for the items to be removed.

I reviewed the code, but I can't test all the My List functionality like email, download, or duplication requests in the interface because a CORS error blocks the Request Broker.

**Comment by helrond** [comment]
OK, got that one taken care of as well. I've also converted the last remaining class components to function components.

You can test at least the Aeon integration by running Request Broker locally and updating your configs to point at that instance. I've tested and feel pretty sure that's working but if you have the time and inclination I would be grateful for another set of eyes. Ping me if you need help getting set up.

**Comment by HaSistrunk** [comment]
Okay, gave the My List features a run-through with the Request Broker running and it's looking good to me too. One last fun thing I noticed:
- The single item "Remove" button removes the item from the list, but then it reappears after several seconds. To reproduce: Add one or more items to list, go to My List page, click "Remove" button, wait a few seconds and see that it will appear again.

**Comment by helrond** [comment]
Hmmm, I can't reproduce this one. 
- Do you see any errors in the console?
- Are you running the request broker locally when this happens?

**Comment by HaSistrunk** [comment]
> Hmmm, I can't reproduce this one.
> 
> * Do you see any errors in the console?
> * Are you running the request broker locally when this happens?

Ok I'm only seeing this when I run request broker locally, but not otherwise. No errors in the console.

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
