### PR TITLE
Adds loading overlay for Record Content

### LINKED ISSUE #245: Add loading indication when opening an object from its url
## Is your feature request related to a problem? Please describe.
From usability testing, we observed that the time it takes to load/scroll to a specific object (as in opening to a specific object's url) can be disorienting or the user does not understand that this is happening.

## Describe the solution you'd like
Add an overlay indicating that the page is loading until it scrolls. Accessibility-wise, focus should be set to the element containing the loading message (if just an icon, give it an aria-label with a loading message), and once it is loaded, transfer focus to the object that loaded.

### PR DESCRIPTION
**Pull request by helrond**
Adds a loading overlay for RecordsContent component which appears when records are loaded from a URL.

@HaSistrunk the styling could definitely use some tweakage, so feel free to mess with that.

fixes #245

### CODE REVIEW

**Comment by helrond** [comment]
@HaSistrunk it looks like that merge might have reverted the query highlight stuff I did yesterday.

**Comment by HaSistrunk** [comment]
> @HaSistrunk it looks like that merge might have reverted the query highlight stuff I did yesterday.

Oh shoot, sorry. I'll revert.

**Comment by HaSistrunk** [comment]
I just tweaked a few things and added some styles for small screens. They should work with the recent changes to improve responsiveness for small screen that are in `base`, and that I am now afraid to merge here.

Do you think we need to keep the overlay from covering the footer, or nah? I was going to do that, but then it got a little tricky with the different screen sizes.

**Review by HaSistrunk — APPROVED** [review]

**Comment by helrond** [comment]
I'm not super worried about the overlay covering the footer - as content loads it will push that footer down and hide the footer anyway.

**Pull request merged**
