### PR TITLE
Improves interactions on MyList page and associated modals

### LINKED ISSUE #162: Improve my list select and remove pattern
## Is your feature request related to a problem? Please describe.
Usability testing showed that users did not clearly understand the conceptual model and functional relationships between the checkboxes and actions including the delete functions.

## Describe the solution you'd like
- Add a confirmation dialog for the Remove All Items button ("Are you sure you want to remove all the items from your list?" with "Cancel" and "Remove" buttons)
- Add a select/deselect all option (this could be another checkbox that aligns with the existing ones)
- Remove the checkboxes on the MyList page, which would shift the selection process to the request modals. This would organize the actions to the My List page (start requests, email, or download), and the selection of which items to include for that specific action to the modal.

## Describe alternatives you've considered
- Leave the checkboxes as they are, and take away the Remove buttons. Replace the "Remove all Items" button with a "Remove Selected Items" button that deletes only the items that have been selected using the checkboxes.

### PR DESCRIPTION
**Pull request by helrond**
Makes a number of changes to MyList page and modals:
- Adds a confirm modal when users click on "remove all items" button
- Adds a select/deselect all button on modals
- Removes checkboxes on main list page

fixes #162

### CODE REVIEW

**Comment by HaSistrunk** [comment]
- Can we tie the select/deselect button to the submit button count?
- Can we make the default be that all items are deselected? I'm hear from folks in Reference that it is extremely common for people to accidentally request everything in their list in the old DIMES. Tied with the form validation error message if nothing is selected, I think that we could help solve that issue with an opt-in approach.

**Comment by HaSistrunk** [comment]
So right now whatever is selected persists, right? Like, if you check one item, close the modal, and then open a different modal, that same one item will be checked. I'd be curious to hear your thoughts on that.

**Comment by helrond** [comment]
OK, I've addressed everything you've noted here. There were a couple bugs and removing the checkboxes in the main list does allow us to remove some complexity in the state object, which I've further clarified here.

**Review by HaSistrunk — APPROVED** [review]
Yay! This looks good!

**Pull request merged**
