### PR TITLE
Dependency updates and language force

### PR DESCRIPTION
**Pull request by p-galligan**
Updates language selection and dependencies.

### CODE REVIEW

**Comment by p-galligan** [comment]
@helrond This is failing because the deploy is failing based on not having AWS S3 access. Is that expected?

**Comment by helrond** [comment]
Yes, that's expected.

**Comment by p-galligan** [comment]
> Yes, that's expected.

Ok, I'll merge to base unless you have any concerns @helrond?

**Comment by helrond** [comment]
Yup, go ahead.

**Pull request merged**
