### PR TITLE
Adds facet modal

### LINKED ISSUE #91: Add modal with facet filters
## Is your feature request related to a problem? Please describe.
Users want to filter results by certain categories.

## Describe the solution you'd like
Add a modal which presents filter options, and filter results based on actions in that modal.

### PR DESCRIPTION
**Pull request by helrond**
Adds a facet modal which filters search results.

Some implementation notes:
- For most of the facets, changes in values trigger an updated search. The exception to this is the dates filter, which is filtered when a user clicks "apply"
- Making a change in a facet does not (right now) close the facet modal.

fixes #91

### CODE REVIEW

**Comment by HaSistrunk** [comment]
Cool, this looks great. I'm getting some weird behavior with the creator checkboxes. When I select one, the facets disappear in the modal/there are no search results.

**Comment by HaSistrunk** [comment]
> Cool, this looks great. I'm getting some weird behavior with the creator checkboxes. When I select one, the facets disappear in the modal/there are no search results.

I think that is just a data pipeline thing, no issue with the code that I can see.

**Review by HaSistrunk — APPROVED** [review]

**Comment by helrond** [comment]
@HaSistrunk can you describe the exact steps which produced this behavior so I can see if I can reproduce?

**Comment by HaSistrunk** [comment]
Initially, when I did a search for "Rockefeller" and tried to facet by Geither, which appeared in the facets as having 1 record, there were no results. However, after I pulled in the most recent version of Argo, that is no longer happening and it is giving the expected results.

However, if I select any of the creator or subject inputs, it gives me only one search results even if the number next to the name indicates more than one results, such as "Bergmann, M. (Max) (3)"

**Comment by helrond** [comment]
OK cool. Yeah it will be interesting to see what users make of this - grouping hits by collection means that you get some differences in the number of "hits" versus the number of tiles in the list. In the case you mention, there are three hits within a single collection.

**Pull request merged**
